name: Deploy TypeScript Microservice to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: fredwinrosales/typescript-api:${{ github.sha }}

      - name: Patch deployment with new image tag
        run: |
          sed -i "s|fredwinrosales/typescript-api:latest|fredwinrosales/typescript-api:${{ github.sha }}|g" k8s/deployment.yaml

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/
